### ISSUE TITLE
Inkscape 1.0

### ISSUE THREAD

**Issue by nanforma** [olibia/inkscape-multipage-export#4]
Hi, Olivia.
A great and useful addition. You plan to fix it for version 1.0.
I tried to edit what the Inkscape swore at. But I am not a programmer, so it did not help. Although there are fewer errors in the output :)

**Comment by olibia** [comment]
Hi @thirtysat, thanks for reporting this. I have started working on the new version, there are some issues I have to fix before releasing it. Will let you know when it's ready.
